### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jinoriosis** [jinoriosis/test#1]
#  Projects

 - [ ] **MIS**
	 - [ ] Server provisioning
	 - [ ] crontab
	 - [ ] Mysql backup
	 - [ ] Account digitalocean
	 - [ ] Datescript
 - [ ] **Rioeasycollect**
	 - [ ] Architecture
	 - [ ] Project brief
	 - [ ] Rioeasycollect installation
	 - [ ] SSL certificate
 - [ ] **MuttatheMulla**
	 - [ ] Servers
 - [ ] **Dropboys**
	 - [ ] Load balancing
	 - [ ] Scaling architecture.

# Tools
 - [ ] DNS Control panel [Resellerclub]
	 - [ ] DNS Name server change
	 - [ ] Support ticket
 - [ ] Ansible
	 - [ ] Muttathemulla server provision
 - [ ] Jenkins
	 - [ ] Update
	 - [ ] Gitlab connection
 - [ ] GitLab
	 - [ ] Update
	 - [ ] Offline GItlab,  Repo Migration Online gitlab
 - [ ] Bulksms
	 - [ ] API key
 - [ ] Google cloud platform
	 - [ ] Bucket Key JSON
	 - [ ] Load balancing 
	 - [ ] Managed instance group
	 - [ ] Template
 - [ ] Zoho Mail
	 - [ ] Configuration
 - [ ] Rocket-chat
	 - [ ] Migration
 - [ ] Webserver
	 - [ ] Rewrite rules
	 - [ ] Apache,nginx,LightHttpd
 - [ ] AWS Workspace

## Servers

 - [ ] Shared
 - [ ] VPS
 - [ ] Single Domain Hosting

## Tasks

 - [ ] Monthly Bill update - Google bill update
 - [ ] MDCB Mail service
 - [ ] Domain Transfer
 - [ ] AMC
 - [ ] Credentials Dinesh,Jino

## Recommendations

 - [ ] Sonarqube
 - [ ] MIS Base Image 
 - [ ] Ansible SSL installation
